spring.application.name=demo
server.port=8081

# Security & JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.access-token-expiration-ms=900000
application.security.jwt.refresh-token-expiration-ms=604800000
application.security.jwt.issuer=teca-ecommerce

# Datasource & JPA configuration (Default: H2 in-memory for instant plug & play
spring.datasource.url=jdbc:postgresql://aws-0-[REGION].pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.[YOUR_PROJECT_REF]
spring.datasource.password=[YOUR_DATABASE_PASSWORD]

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

